[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200